
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-15
owner: ucsb-cs156-s26
repo_name: team01-s26-15
pull_requests: [{"author":{"id":"U_kgDOCuio7Q","is_bot":false,"login":"joyycheng","name":"Joy Cheng"},"headRefName":"joy-ucsborganizations-get-by-id","number":67,"title":"Joy -  add GET by id for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/67"},{"author":{"id":"U_kgDOC5bJ1g","is_bot":false,"login":"katelyn-dang","name":""},"headRefName":"kd-delete-for-menuitemreview","number":66,"title":"kd - add delete endpoint to menu item review controller; tests will be in next commit","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/66"},{"author":{"id":"U_kgDOCuio7Q","is_bot":false,"login":"joyycheng","name":"Joy Cheng"},"headRefName":"joy-ucsborganizations-controllers","number":64,"title":"joy - create ucsborganizations controller","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/64"}]
