
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-15
owner: ucsb-cs156-s26
repo_name: team01-s26-15
pull_requests: [{"author":{"id":"U_kgDOCuio7Q","is_bot":false,"login":"joyycheng","name":"Joy Cheng"},"headRefName":"joy-delete-for-organizations-table","number":69,"title":"Joy - delete for organizations table","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/69"},{"author":{"id":"U_kgDOCuio7Q","is_bot":false,"login":"joyycheng","name":"Joy Cheng"},"headRefName":"joy-put-for-organizations-table","number":68,"title":"jc - add test coverage to PUT","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/68"}]
