
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-15
owner: ucsb-cs156-s26
repo_name: team01-s26-15
pull_requests: [{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-readme-update","number":55,"title":"mf - readme update","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/55"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-ucsbdcmi-delete","number":54,"title":"mf - ucsbdcmi delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/54"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-ucsbdcmi-put-for-table","number":53,"title":"mf - ucsbdcmi put for table","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/53"},{"author":{"id":"U_kgDOC0_I2w","is_bot":false,"login":"SteveZhaoUcsb","name":"Xuanbo Zhao"},"headRefName":"xuanbo-put-for-article-table","number":52,"title":"xuanbo put for article table","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/52"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-ucsbdcmi-get-by-id","number":50,"title":"mf - add GET by id for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/50"},{"author":{"id":"U_kgDOCuio7Q","is_bot":false,"login":"joyycheng","name":"Joy Cheng"},"headRefName":"joyycheng-UCSBOrganization-create-db","number":47,"title":"joy - create db for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/47"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-ucsbdcmi-controller","number":46,"title":"mf - create ucsbdcmi controller","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/46"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"Mikaela-UCSBDiningCommonsMenuItem","number":45,"title":"mf - create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/45"},{"author":{"id":"U_kgDOCxz58A","is_bot":false,"login":"schoolKris08","name":"Kristopher Rangel-Olivos"},"headRefName":"Kristopher-HelpDT","number":43,"title":"Kristopher helpReqeust Create DataTable","url":"https://github.com/ucsb-cs156-s26/team01-s26-15/pull/43"}]
